### ISSUE TITLE
[Question] How can I use GAS with Enhanced Inputs?

### ISSUE THREAD

**Issue by aadeshrao123** [tranek/GASDocumentation#105]
How can I use GAS with Enhanced Inputs?

**Comment by tranek** [comment]
Lyra is a good example for this. I don't have any plans at this time to extend GASDocumentation with EnhancedInput, but it would be a good addition along with a few other things if I ever get the time.

**Comment by aadeshrao123** [comment]
> Lyra is a good example for this. I don't have any plans at this time to extend GASDocumentation with EnhancedInput, but it would be a good addition along with a few other things if I ever get the time.

Your documentation is way better than Lyra's. In Lyra, I am too confused about how they implement those inputs. I will be waiting for your documentation for the Enhanced Inputs system in GAS.

**Comment by tranek** [comment]
I appreciate the complement but you might be waiting a very long time (potentially forever).
