### ISSUE TITLE
Possible unnecessary cast in PlayMontageAndWaitForEvent

### ISSUE THREAD

**Issue by tommygod3** [tranek/GASDocumentation#109]
I can't seem to see any reason we have to cast the ASC to a `UGDAbilitySystemComponent` in this class? In which case this may be an unnecessary cast:
https://github.com/tranek/GASDocumentation/blob/f986a00d224ebfb79472fa6ba37738d0bf926347/Source/GASDocumentation/Private/Characters/Abilities/AbilityTasks/GDAT_PlayMontageAndWaitForEvent.cpp#L22

**Comment by tranek** [comment]
Thanks! It was probably copied over from Epic's ARPG sample project.

**Comment by tommygod3** [comment]
No worries, thank you for the fix! I would have put in a PR myself but have been looking into another issue: https://github.com/tranek/GASDocumentation/issues/111
