### ISSUE TITLE
StaticLoadClass DamageNumberClass doesn't work when packaged

### ISSUE THREAD

**Issue by tommygod3** [tranek/GASDocumentation#110]
This runs fine in PIE but when I package the project and run I get a null pointer error (and obviously the error log) because this `StaticLoadClass` doesn't seem to work once the game is packaged:
https://github.com/tranek/GASDocumentation/blob/f986a00d224ebfb79472fa6ba37738d0bf926347/Source/GASDocumentation/Private/Player/GDPlayerController.cpp#L58
Does there need to be a project setting to include this in the build? Other usages seem to work okay

**Comment by tranek** [comment]
Fixed with https://github.com/tranek/GASDocumentation/commit/80a616a9ef052cfc8293608b2b5e148fdf32e239
