### ISSUE TITLE
Load gameplay tags from .ini in a Plugin/Config folder

### ISSUE THREAD

**Issue by EnricoPietrocola** [tranek/GASDocumentation#125]
How can we define gameplay tags in a .ini file contained in the config folder of a plugin?
I am trying but it won't load anything, I can only get to initialize correctly if the file is contained in the main project Config folder and only if the file is called "DefaultGameplayTags.ini"

**Comment by ameaninglessname** [comment]
Ini file in **Config/Tags**  folder would be scaned, you could refer to other plugins in the engine.

**Comment by EnricoPietrocola** [comment]
Thank you for helping me

> Ini file in **Config/Tags** folder would be scaned, you could refer to other plugins in the engine.

From the Plugins config folder? I have checked all engine plugins and I don't see any doing that, do you happen to have one I could reference from?

> Here's how the CommonConversation plugin does it:
>void FCommonConversationRuntimeModule::StartupModule()
>{
>	TSharedPtr<IPlugin> ThisPlugin = IPluginManager::Get().FindPlugin(TEXT("CommonConversation"));
>	check(ThisPlugin.IsValid());
>	
>	UGameplayTagsManager::Get().AddTagIniSearchPath(ThisPlugin->GetBaseDir() / TEXT("Config") / TEXT("Tags"));
>}

I see, so there's no way to actually do this without impllementing loading, I though that .ini files were all scanned and loaded at startup

**Comment by ameaninglessname** [comment]
> Thank you for helping me

Sorry, my memory was corrupted, `tranek` is right.

After putting these code in `FOneOfYourModule::StartupModule`, my saying is valid:
```cpp
for (const TSharedPtr<const IPlugin> ThisPlugin : IPluginManager::Get().GetEnabledPluginsWithContent())
{
    if (FString TagsIniDirectory = ThisPlugin->GetBaseDir() / TEXT("Config") / TEXT("Tags");
        FPaths::DirectoryExists(TagsIniDirectory))
    {
        SOME_LOG_FUNCTION(LogRemAutoAddTagIniSearchPath, Log,
            TEXT("TagIniSearchPath: {0} Added"), TagsIniDirectory);

        UGameplayTagsManager::Get().AddTagIniSearchPath(TagsIniDirectory);
    }
}
```

**Comment by tranek** [comment]
> I see, so there's no way to actually do this without impllementing loading, I though that .ini files were all scanned and loaded at startup

If you call `UGameplayTagsManager::Get().AddTagIniSearchPath()` in your `StartupModule()`, any .ini files in that directory will be scanned and loaded from your plugin at startup.

**Comment by Ciberusps** [comment]
Hey how to load gameplay tags from project `GameplayTagTableList` in plugin?
Looks like UGameplayTagsManager::Get().LoadGameplayTagTables(); dont work

UPD found solution, my plugin load order was `PreLoadingScreen`, so I changed on `Default`
