### ISSUE TITLE
How to use target attributes to define if a gameplay effect can be applied

### ISSUE THREAD

**Issue by reisandbeans** [tranek/GASDocumentation#146]
I want my characters to have an attribute that defines their resistance to status effects. The higher their resistance, the lower the chance it will be applied. I checked the existing gameplay effect components available, and `ChanceToApplyGameplayEffectComponent` is not good, since it just has a `FScalableFloat` that defines the raw chance, it doesn`t let me do more complex calculations. 

In section [4.5.13](https://github.com/tranek/GASDocumentation?tab=readme-ov-file#4513-custom-application-requirement) it is mentioned that we can use CustomApplicationRequirement to check if the **Target** has a certain amount of an attribute, but I've failed to find how to do that. I couldn't find a way to add capture definitions to `GameplayEffectComponent`s and `CustomApplicationRequirement`s (I did find the code that capture those definitions, and they seem to only take into account modifiers, duration, and executions, no mention of components whatsoever - see screenshot below. Also those captures happen **after** the check for `CanApply`).

Does anybody know how to access Target attributes in `CustomApplicationRequirement`, or perhaps another way of achieving what I'm looking for?

![image](https://github.com/user-attachments/assets/170ba2d7-963f-40bb-af70-0bddd0524a8c)

**Comment by tranek** [comment]
```
bool CanApplyGameplayEffect(const UGameplayEffect* GameplayEffect, const FGameplayEffectSpec& Spec, UAbilitySystemComponent* ASC) const;
```

The ASC parameter is the target. You can get its attributes from that.
