### ISSUE TITLE
Crash when calling InitGlobalData from EngineSubsystem

### ISSUE THREAD

**Issue by fpwong** [tranek/GASDocumentation#17]
Replicate crash by adding a attribute set table in `DefaultGame.ini` as below:

`[/Script/GameplayAbilities.AbilitySystemGlobals]
+GlobalAttributeSetDefaultsTableNames=/Game/DataTables/InitialAttributes.InitialAttributes` 

Crash will occur due to trying to bind to delegate 

`GEditor->GetEditorSubsystem<UImportSubsystem>()->OnAssetReimport.AddUObject(this, &UAbilitySystemGlobals::OnTableReimported);`

In the function `UAbilitySystemGlobals::InitAttributeDefaults`

Guessing this crashes since the EngineSubsystem is initialized before the EditorSubsystem

Suggested fix is to call `InitGlobalData` from the GameInstance instead

**Comment by tranek** [comment]
I won't change the Sample Project because this crash is not relevant to it, but I did add a note to the README about it.

Thanks for the heads up!
