### ISSUE TITLE
Copy paste error 4.6 Critical Hits

### ISSUE THREAD

**Issue by DRaineri** [tranek/GASDocumentation#20]
Change 

> The ExecutionCalculation checks if the GameplayEffectSpec has that **Effect.CanLifesteal** GameplayTag

to 

> The ExecutionCalculation checks if the GameplayEffectSpec has that **Effect.CanCrit** GameplayTag

Btw, thank you very much for this documentation ! It's very good ^^

**Comment by tranek** [comment]
Thanks! The fix will be with the 4.25/GASShooter update to the doc. I'll close the issue when that's pushed to GitHub (when 4.25 is out of Preview at the earliest).
