### ISSUE TITLE
suggestion about SendEventToActor function

### ISSUE THREAD

**Issue by blueroseslol** [tranek/GASDocumentation#27]
# GameplayTag 
GameplayTag must be a sub-tag of event,otherwise RPGAbilityTask_PlayMontageAndWaitForEvent will not receive event.

# Payload(GameplayEventData)
GameplayEventData have OtionalObject parameter.Through a UObject to send more data.
In blueprint,you can use "Construct Object".Instantiate an UObject asset as input.
And When an event is received.You can get this UObject instance.

I think this is very useful.And hope you can add to document.

**Comment by tranek** [comment]
The `PlayMontageAndWaitForEvent` `AbilityTask` can receive any tag. The implementations in the ARPG sample project have a filter of `Event.Montage` on them as a parameter on the Blueprint node. Change that `EventTags` parameter in Blueprint and you'll see it receive all tags that come from gameplay events.

I already mention using optional objects when passing data through GameplayEvents for sharing arbitrary data. https://github.com/tranek/GASDocumentation#concepts-ga-data

> Use the two Optional Object variables for arbitrary data that does not fit any of the existing variables.

Thank you for your feedback.

**Comment by blueroseslol** [comment]
Thanks for your reply.
