### ISSUE TITLE
ListenForAttributeChange crashes editor when changing attribute values

### ISSUE THREAD

**Issue by doctor-g** [tranek/GASDocumentation#28]
Steps to reproduce:

1. Open the project in Unreal Engine 4.25
2. In UI_HUD, fiddle the Attribute value in ListenForAttributeChange. Alternatively, change the value of the array for ListenForAttributesChange.
3. Saving the blueprint causes an editor crash.

**Comment by tranek** [comment]
It's an engine bug in 4.25 - all BP nodes (`GetFloatAttribute` for example) with `Attributes` as parameters cause this crash. I submitted a bug report to Epic. I'll comment again with the issue # when they confirm it. Good find!

**Comment by tranek** [comment]
In the meantime, you can convert all of the `Attribute` pins to variables. That does not crash.

**Comment by tranek** [comment]
Bug report has been accepted. Issue UE-92787

https://issues.unrealengine.com/issue/UE-92787

**Comment by doctor-g** [comment]
Great, thanks for posting the UE bug and especially for providing the workaround. I couldn't decipher what exactly was going wrong; I'm glad you were able to isolate it more carefully.

**Comment by MedzerLexpert** [comment]
Do we have news about this ? It still crashes for me :<

**Comment by tranek** [comment]
4.25.1, released today, fixes the crash.
