### ISSUE TITLE
Projectile Issue

### ISSUE THREAD

**Issue by andgeno** [tranek/GASDocumentation#3]
Hi,

I'm not sure if this is out of scope of GAS but I noticed the following issue.

When I shoot at a minion from a certain distance shot projectiles fly right through the target. I think this is because the projectile is seen by the physics engine only in front and behind the target when it ticks. So I tried the projectile shots from the same position/angle/distance using `Slomo .01` which seems to "fix" this because it probably gives the physics engine more time to actually see the projectile hitting the target.

Here's a short video that demonstrates this:
https://youtu.be/YSxnr08OVBc

Can this be solved using GAS? Maybe some sort of sweep collision tests?

**EDIT**
I forgot to mention an important detail! This seems to only happen when the game is run as a **standalone** application.

**Comment by tranek** [comment]
It was a projectile collision bug, unrelated to GAS. The issue is not present in UE 4.24 which is weird. Swapping from using the sphere static mesh to a sphere component for the collision fixed it on my end.

**Comment by andgeno** [comment]
Cool, thanks for the fix. :-)
