### ISSUE TITLE
AttributeSet's Health Current Value, how to change by Damage

### ISSUE THREAD

**Issue by marshal-it** [tranek/GASDocumentation#30]
if role up health with duration, the health's CurrentValue(like temporary, time out will recover), but the damage is instant, will change health's BaseValue. so if I want the damage change health's CurrentValue, how to do?

**Comment by tranek** [comment]
Hello,

Any attribute that is a resource (health is a resource) should have GameplayEffects that only change its base value and we use two attributes to represent its current state and its max state - Health and MaxHealth.

If you want health to recover over time, you would use an infinite duration, periodic GameplayEffect that would regenerate the health.

If you actually want "temporary health" on top of a player's normal health, then you should create two new attributes - TemporaryHealth and MaxTemporaryHealth, just like we would do for a shield. In that sense temporary health is really just a temporary shield.

The GitHub Issues are for problems (bugs) with the Sample Project or the documentation. Please ask questions about using GAS on the Unreal Slackers Discord https://unrealslackers.org/ or the official Unreal Engine forums https://forums.unrealengine.com/.
