### ISSUE TITLE
Problem in Animation Instance

### ISSUE THREAD

**Issue by oivio** [tranek/GASDocumentation#32]
I am using plugin "AnimIK" from the marketplace. Basically I do create with it **Animation Blueprint**. After, setting all things in that AnimBP. I do use from that plugin the custom **FullbodyIK** node in **AnimGraph** what is pined to **OutputPose** Everything works fine until I do restart the project. After it **FullbodyIK** node always does disappears, like it ha been removed. I did test it on GAShooter temple as well and the same problem. I did also test on ActionRPG temple that uses GAS and there works fine. 
I am not really good with coding, still learning so it is hard for me to track the bug or find the reason why it is happening.

I did test also with some other plugin and I am having the same issue.

**Comment by tranek** [comment]
I do not have that plugin from the marketplace and I don't know anything about it. These sample projects focus on GAS techniques, not animation techniques. My Anim Blueprints probably are not the best examples. You might want to try making your own Anim Blueprint from scratch.

This isn't an issue with my sample projects as they are - I do not provide support for any third party plugins. Best of luck.
