### ISSUE TITLE
Clarification about GameplayDebuger

### ISSUE THREAD

**Issue by strievich** [tranek/GASDocumentation#35]
>Use the Gameplay Debugger when you want to see the GameplayTags, GameplayEffects, and GameplayAbilities on **other** Characters. Unfortunately it does not show the CurrentValue of the target's Attributes. It will target whatever Character is in the center of your screen. Look at a different Character and press Apostrophe (') again to switch to inspecting its ASC. The currently inspected Character has the largest red circle above it."

In PIE mode you can select any character in the Wolrld Outline tab. That character will become Debug Actor(it name will be displayed in  top right corner). If that character has a GAS component then its parameters will be displayed in the Gameplay Debugger.

**Comment by tranek** [comment]
Thanks for the tip!
