### ISSUE TITLE
Quickly and massively activating ability to modify Heath values causes the server to lag behind in synchronizing to the client

### ISSUE THREAD

**Issue by ouyang-yuxuan** [tranek/GASDocumentation#41]
My own project quickly and massively activated the ability to modify the Heath value, which would cause the server to lag behind the client. In fact, the intermediate value of a large number of changes was lost, and the derivative UI displayed intermittently.But in this case, it can be synchronized in a timely manner. Would you please tell me? I'm not very good at c++.

**Comment by tranek** [comment]
This Issues section is for problems with the GASDocumentation sample project or the README. For support in your own projects, try the [Unreal Engine Forums](https://forums.unrealengine.com/) or [Unreal Slackers Discord Server](https://unrealslackers.org/).
