### ISSUE TITLE
Question & Doc Suggestion: ASC for RTS Games, PlayerState own all unit avatars?

### ISSUE THREAD

**Issue by SyedAman** [tranek/GASDocumentation#42]
How would you implement ASCs for a RTS game, I know MOBA is referred to here though which is similar.

From reading the docs for GAS implementation for a RTS game, I am not 100% sure if I should be 
A) adding the ASC to the PlayerState as the OwnerActor and making all units AvatarActors owned by the PlayerState ASC
B) or if I should be adding separate individual ASCs for every unit and every unit is its own Avatar and OwnerActor.

I went with B and I am currently running into problems binding unit abilities to player input since Player Controller doesn't control the units.

I think doc might benefit if RTS is mentioned

**Comment by tranek** [comment]
Unfortunately, I don't know the best way to set up an RTS game with GAS. It was a future sample project that I wanted to research and make, but never got around to it and I don't have time at the moment or for the foreseeable future. I imagine that each unit will need its own ASC to keep track of its own health attribute and other attributes and abilities. I'd recommend reaching out to the [Unreal Slackers Discord Server](https://unrealslackers.org/) to see if anyone else has done it or at least start a conversation about it.

If someone else creates a well-made RTS sample project, I'd be open to linking to its GitHub repository and accepting PRs to the README with info about it.

**Comment by SyedAman** [comment]
If anyone comes across this issue, here is an inspiring resource of a team that made a RTS using GAS:

https://www.youtube.com/watch?v=1Dm1G6fUuFs
