### ISSUE TITLE
Custom Trace Profile / Collision Preset

### ISSUE THREAD

**Issue by VonHirsch** [tranek/GASDocumentation#43]
I noticed the project has a Custom Channel "Ability" and custom Preset "TargetActorGroundLocation"

Are those critical to the project, and if so should they be documented?

Reason I ask, I'm trying to implement the Meteor GA in C++.  I know I have to take care of the "K2Node_LatentGameplayTaskCall automagic sorcery" myself, but for some reason the target just paints at 0,0,0 but doesn't animate or track when I move around.  I've been stepping through the code and thought maybe I'm missing some configuration regarding collisions.

![image](https://user-images.githubusercontent.com/3280180/101266599-3dc80f80-371e-11eb-8b2e-e597cfeaf218.png)

**Comment by tranek** [comment]
Hello. I wouldn't call the custom channel and profile critical, but that AbilityTask does need a Trace Profile that collides (blocks) with the ground (World Static/Dynamic).

Custom channels and profiles are up to the developers. Most games will make their own channels for things like hitscan bullets and projectiles. Some games might reuse those for abilities or make their own separate ones for abilities. Some games may want their abilities to ignore other abilities in flight or they may want their fireballs to collide with each other. That's more of a general UE4 thing and less of a GAS thing so I will not include it in the docs as it's very game specific.

**Comment by VonHirsch** [comment]
Sounds good.  Incidentally, I got it working in C++, I had missed the step to set the StartLocation of the SpawnedActor instance after calling WaitTargetData.

		// Get Player & Show HUD Message
		AXBZTGasSandboxCharacter* Player = CastChecked<AXBZTGasSandboxCharacter>(ActorInfo->AvatarActor.Get());
		Player->ShowAbilityConfirmCancelText(true);
		// Create WaitTargetData
		UAbilityTask_WaitTargetData* WaitTargetData = UAbilityTask_WaitTargetData::WaitTargetData(this, FName("Place WaitTargetData"), EGameplayTargetingConfirmation::UserConfirmed, InTargetClass);
		AGameplayAbilityTargetActor* SpawnedActor;

		//To reiterate, K2Node_LatentGameplayTaskCall only does automagic sorcery for Blueprint.
		// In C++, we have to manually call ReadyForActivation(), BeginSpawningActor(), and FinishSpawningActor().

		WaitTargetData->ReadyForActivation();
		WaitTargetData->BeginSpawningActor(this, InTargetClass, SpawnedActor);
		WaitTargetData->FinishSpawningActor(this, SpawnedActor);

		FGameplayAbilityTargetingLocationInfo TargetingLocationInfo = MakeTargetLocationInfoFromOwnerActor();
		// Set targeting location to the front and ahead of the Player
		TargetingLocationInfo.LiteralTransform.SetLocation(Player->GetActorForwardVector() * 200 + TargetingLocationInfo.LiteralTransform.GetLocation());
		//Assign TargetingLocationInfo to Targe Actor Instance - this is what I was missing
		SpawnedActor->StartLocation = TargetingLocationInfo;
