### ISSUE TITLE
Problem with AttributeSetBase when no default pawn class chosen

### ISSUE THREAD

**Issue by tommygod3** [tranek/GASDocumentation#45]
Apologies if this issue is not relevant to the repo, however, with some experimenting with the example project it is reasonably easy to reproduce. 
I have changed the game mode BP to have no default pawn and added a spawn function which creates a BP_HeroCharacter and posseses it with the player controller. This would be useful if you wanted a character select screen for example.
![Capture](https://user-images.githubusercontent.com/32672006/104229107-b3bd4600-5443-11eb-8869-02312c7999f7.PNG)
When this spawn function is triggered from the PC's begin play everything seems to work fine, however, when this function is triggered in play instead, some weird behaviour happens. 
When using a listen server and client, the listen server is setup correctly but the client's call to `PS->GetAttributeSetBase()` returns all the attributes set to 0.
https://github.com/tranek/GASDocumentation/blob/3575672b22d5bfc4508f07b3ecb17479b18f5721/Source/GASDocumentation/Private/Characters/Heroes/GDHeroCharacter.cpp#L282
![Capture1](https://user-images.githubusercontent.com/32672006/104229994-e451af80-5444-11eb-8a04-cd9ce4891854.PNG)
This causes the client to die because its max health is set to 0.
https://github.com/tranek/GASDocumentation/blob/3575672b22d5bfc4508f07b3ecb17479b18f5721/Source/GASDocumentation/Private/Characters/Heroes/GDHeroCharacter.cpp#L304

Again, apologies if this kind of issue is out of scope, however, it seems to me to be connected to how the AbilitySystemComponent is setup in this project so I thought it might be useful to ask here.

**Comment by tommygod3** [comment]
I should maybe add that when I say the client dies, this is only on the client side. The client gains the State.Dead tag but is not destroyed or given a respawn timer as the server never sees the client die.
![Capture2](https://user-images.githubusercontent.com/32672006/104232682-99d23200-5448-11eb-9ae9-f77a371b5068.PNG)

**Comment by tommygod3** [comment]
The end result of this is that on the first spawn the client sees their movement as very laggy and they cannot use any abilities (because they think they died). On subsequent spawns however, the AbilitySystemComponent sets the AttributeSetBase up properly and this does not happen.

**Comment by tommygod3** [comment]
Upon further review it seems that when a client calls `InitializeAttributes()`, the default attributes are not initialised. 
https://github.com/tranek/GASDocumentation/blob/3575672b22d5bfc4508f07b3ecb17479b18f5721/Source/GASDocumentation/Private/Characters/Heroes/GDHeroCharacter.cpp#L286
However, on the listen server, `AttributeSetBase` seems to already be set correctly before the client version of InitializeAttributes() is called. Perhaps I am misunderstanding the InitializeAttributes() function but it seems like it should work for both server and client as suggested here: https://github.com/tranek/GASDocumentation/blob/3575672b22d5bfc4508f07b3ecb17479b18f5721/Source/GASDocumentation/Private/Characters/GDCharacterBase.cpp#L304

**Comment by tranek** [comment]
Unfortunately that is out of the scope of this repo. You may want to look into alternate ways of initializing the attributes if that is a problem for your game -- for example you can set default values greater than zero in the constructor for the health AttributeSet.

**Comment by tommygod3** [comment]
Fair enough, I presumed it was a bug as there was inconsistent behaviour between client and server but now I think perhaps there just needs to be a check like you suggest when I try to initialise this way.
