### ISSUE TITLE
Warnings when using stat gpu command

### ISSUE THREAD

**Issue by xSpeedy197** [tranek/GASDocumentation#47]
When using stat gpu command, there is this warning
![image](https://user-images.githubusercontent.com/52882811/107532026-1c741b80-6bc6-11eb-88b0-f1393a3a7a4a.png)

**Comment by xSpeedy197** [comment]
This happens even in an empty level with default game mode.

**Comment by Bit-Rot** [comment]
If this is happening in an empty level with the default game mode, it stands to reason that this probably doesn't have to do with the GASDocumentation repository?

**Comment by xSpeedy197** [comment]
> If this is happening in an empty level with the default game mode, it stands to reason that this probably doesn't have to do with the GASDocumentation repository?
Yes I found out later, this seems to happen in ActionRPG sample, OWS plugin, and my project based on GAS Documentation. On another project that is on 4.23 version with GAS plugin implemented from Udemy tutorial this warning doesn't show. So these projects share something that make this warning appear. I was hoping someone knows what this warning is about. My bet was that this enum is causing it "enum class EGDAbilityInputID" I deleted UMETA(DisplayName = "...") and it's still there. Could this break something in the engine after the first compilation? This is certainly a warning relevant to GASDocumentation, if I'm not allowed to post something like this here, you can simply say, no need to act like I'd be stupid ("stands to reason")

**Comment by Bit-Rot** [comment]
Certainly no offense intended.

As you suggested, the issues section on this repo isn't intended for general engine/GAS-plugin related issues, but rather for issues with the GASDocumentation project itself.  

It's possible you may be able to find help on the UnrealSlackers discord, or the unrealengine subreddit or forums, though.  The discord has a gameplay-abilities-plugin channel which may be particularly helpful.

**Comment by xSpeedy197** [comment]
Ok, at first I thought it's something with the code from GASDocumentation as I didn't have this bug in my test project with GAS on 4.23. I also tested on a friend's pc in case it's something with my gpu, and it acts the same there. Do you not get that warning in output log when using stat gpu command?

**Comment by tranek** [comment]
I'm seeing this in Epic's ActionRPG and ShooterGame, too. This question should be posted on UE's official forums or Unreal Slackers Discord. This is not specific to GASDocumentation so I'm closing this Issue.
