### ISSUE TITLE
Instant GEs Cannot Grant Abilities -- Correct?

### ISSUE THREAD

**Issue by GuyPaddock** [tranek/GASDocumentation#69]
From my own testing, it seems that an instant GE cannot grant abilities. Is that correct, or am I mistaken? I didn't see anything in the docs either way.

**Comment by Oldsiren** [comment]
Yes they cannot grant abilities, that is only done with GE's that have a duration/infinite. A hacky workaround is to set the duration for 1 frame(so it removes itself for next frame) and that will follow the rules of granting an ability

**Comment by GuyPaddock** [comment]
Found it -- covered in https://github.com/tranek/GASDocumentation#456-granted-abilities
