### ISSUE TITLE
IAbilitySystemInterface usage at 2 places.

### ISSUE THREAD

**Issue by ANURAGX** [tranek/GASDocumentation#7]
Hi buddy,
First of really thanks for wonderful work and sharing it.
I got confused since you are using **IAbilitySystemInterface** for PlayerState and BaseCharacter class.

Can you explain your logic please?

**Comment by ANURAGX** [comment]
`
UAbilitySystemComponent * AGDCharacterBase::GetAbilitySystemComponent() const
{
	         return AbilitySystemComponent.Get();
}`

Does this return the AbilitySystemComponent from PlayerState?

**Comment by tranek** [comment]
For the `AGDHeroCharacter`, yes. For the `GDMinionCharacter`, it returns a pointer to the `HardRefAbilitySystemComponent` on the `GDMinionCharacter`.

Subclasses are responsible for creating and owning the ASC and setting the weak pointer on the base class. Same with the AttributeSet.

This isn't the only way to architect it, but it is intuitive to me.

**Comment by ANURAGX** [comment]
Thanks for clarification.
