### ISSUE TITLE
Suggestion for section 4.11.1 (Target Data)

### ISSUE THREAD

**Issue by YawLighthouse** [tranek/GASDocumentation#75]
Pull Request: https://github.com/tranek/GASDocumentation/pull/102
At the end of the section it talks about how Target Data is polymorphic so you can add your own types but nowhere in the code or in the document is it explained on get your custom `FGameplayAbilityTargetData` from a `FGameplayAbilityTargetDataHandle`, the source code only shows examples of overriding the base functions inside `FGameplayAbilityTargetData` and using those. I wanted to suggest adding examples for how to add a custom `FGameplayAbilityTargetData` to a `FGameplayAbilityTargetDataHandle` and an example of how to get that custom `FGameplayAbilityTargetData` from the handle to get custom values.
As a suggestion(you're totally welcome to rip this apart and say the code is bad I just want to help improve the documentation as much as possible):
Declaring the custom `FGameplayAbilityTargetData`
```
USTRUCT(BlueprintType)
struct MYGAME_API FGameplayAbilityTargetData_CustomData : public FGameplayAbilityTargetData
{
        GENERATED_BODY()
public:

        FGameplayAbilityTargetData_CustomData()
        { }

        UPROPERTY()
        FName CoolName = NAME_None;

        UPROPERTY()
        FPredictionKey PredictionForAbility;

	// This is required for all child structs of FGameplayAbilityTargetData
	virtual UScriptStruct* GetScriptStruct() const override
	{
		return FGameplayAbilityTargetData_CustomData::StaticStruct();
	}

	// This is required for all child structs of FGameplayAbilityTargetData
        bool NetSerialize(FArchive& Ar, class UPackageMap* Map, bool& bOutSuccess)
        {
                CoolName.NetSerialize(Ar, Map, bOutSuccess);
                PredictionForAbility.NetSerialize(Ar, Map, bOutSuccess);
                bOutSuccess = true;
                return true;
        }
}

template<>
struct TStructOpsTypeTraits<FGameplayAbilityTargetData_CustomData> : public TStructOpsTypeTraitsBase2<FGameplayAbilityTargetData_CustomData>
{
	enum
	{
		WithNetSerializer = true // This is REQUIRED for FGameplayAbilityTargetDataHandle net serialization to work
	};
};

```
And for adding the value to a handle
```
FGameplayAbilityTargetData_CustomData* CustomData = new FGameplayAbilityTargetData_CustomData();
CustomData->CoolName = FName("Hello there!");
FGameplayAbilityTargetDataHandle Handle;
Handle.Add(CustomData);
```
And for getting the value/safely casting
```
FGameplayAbilityTargetData* data = Handle.Data[0].Get();
// Valid check we have something to use :D
if(data == nullptr)
{
    return;
}
// This is basically the type checking pass, static_cast does not have type safety, this is why we do this check. If we don't do this then it will object slice(google it if you don't know what that is) the struct and we have no way of making sure its that type, 
// Another approach is to input gameplay tag(s) and filter based on that gameplay tag(s), different ways to do stuff sort of thing
if(data->GetScriptStruct() == FGameplayAbilityTargetData_CustomData::StaticStruct())
{
    // Here is when you would do the cast
    FGameplayAbilityTargetData_CustomData* CustomData = static_cast<FGameplayAbilityTargetData_CustomData*>(data);
}
```

**Comment by cupsster** [comment]
Than you, I was wondering as well and used `static_cast` which is sub-optimal.

**Comment by Hookist** [comment]
Could you show the .NetSerialize function for FName please?

**Comment by asynchronoust** [comment]
`static_cast` is not safe, when cast the child to parent. @cupsster 


I have encountered a cast that the result after casted is not correct, the memory layout is error.  The pointer `CustomData` is not the nullptr, but it crashed when i use the pointer to accesss member property.
`FGameplayAbilityTargetData_CustomData* CustomData = static_cast<FGameplayAbilityTargetData_CustomData*>(Handle.Data[0].Get());`

**Comment by YawLighthouse** [comment]
@asynchronoust Yup thats part of working with C & C++ its basically object slicing the object for only the certain type and there is no type safety when dealing with those casts, if you wanna do a type safety check you would do 

```
FGameplayAbilityTargetData* data = Handle.Data[0].Get();
if(data->GetScriptStruct() == FGameplayAbilityTargetData_CustomData::StaticStruct())
{
    // Here is when you would do the cast
    FGameplayAbilityTargetData_CustomData* CustomData = static_cast<FGameplayAbilityTargetData_CustomData*>(Handle.Data[0].Get());
}
```
