### ISSUE TITLE
How Jump Abiity works?

### ISSUE THREAD

**Issue by ANURAGX** [tranek/GASDocumentation#8]
Hi again,
I couldn't  find the reference where the JumpAbility is being bind to the Spcaebar key binding.

**Comment by tranek** [comment]
In the project input settings I have an input action for Jump.

In `GASDocumentation.h` there's a struct of all the input bindings that are bound to the ASC:

```c++
UENUM(BlueprintType)
enum class EGDAbilityInputID : uint8
{
	// 0 None
	None			UMETA(DisplayName = "None"),
	// 1 Confirm
	Confirm			UMETA(DisplayName = "Confirm"),
	// 2 Cancel
	Cancel			UMETA(DisplayName = "Cancel"),
	// 3 LMB
	Ability1		UMETA(DisplayName = "Ability1"),
	// 4 RMB
	Ability2		UMETA(DisplayName = "Ability2"),
	// 5 Q
	Ability3		UMETA(DisplayName = "Ability3"),
	// 6 E
	Ability4		UMETA(DisplayName = "Ability4"),
	// 7 R
	Ability5		UMETA(DisplayName = "Ability5"),
	// 8 Sprint
	Sprint			UMETA(DisplayName = "Sprint"),
	// 9 Jump
	Jump			UMETA(DisplayName = "Jump")
};
```

`GDHeroCharacter` binds the `InputComponent` to the ASC using that struct as a mapping.

```c++
void AGDHeroCharacter::BindASCInput()
{
	if (!ASCInputBound && AbilitySystemComponent.IsValid() && IsValid(InputComponent))
	{
		AbilitySystemComponent->BindAbilityActivationToInputComponent(InputComponent, FGameplayAbilityInputBinds(FString("ConfirmTarget"),
			FString("CancelTarget"), FString("EGDAbilityInputID"), static_cast<int32>(EGDAbilityInputID::Confirm), static_cast<int32>(EGDAbilityInputID::Cancel)));

		ASCInputBound = true;
	}
}
```

A `EGDAbilityInputID` is stored on the `UGDGameplayAbility` class (set manually in the blueprint or C++ constructor of the ability subclass) that I read from when I grant the ability to the ASC that tells it to associate that ability with that input action.

```c++
void AGDCharacterBase::AddCharacterAbilities()
{
	// Grant abilities, but only on the server	
	if (GetLocalRole() != ROLE_Authority || !AbilitySystemComponent.IsValid() || AbilitySystemComponent->CharacterAbilitiesGiven)
	{
		return;
	}

	for (TSubclassOf<UGDGameplayAbility>& StartupAbility : CharacterAbilities)
	{
		AbilitySystemComponent->GiveAbility(
			FGameplayAbilitySpec(StartupAbility, GetAbilityLevel(StartupAbility.GetDefaultObject()->AbilityID), static_cast<int32>(StartupAbility.GetDefaultObject()->AbilityInputID), this));
	}

	AbilitySystemComponent->CharacterAbilitiesGiven = true;
}
```

Jump's input action `EGDAbilityInputID` is set in the ability constructor.

```c++
UGDGA_CharacterJump::UGDGA_CharacterJump()
{
	AbilityInputID = EGDAbilityInputID::Jump;
	InstancingPolicy = EGameplayAbilityInstancingPolicy::NonInstanced;
	AbilityTags.AddTag(FGameplayTag::RequestGameplayTag(FName("Ability.Jump")));

}
```

Any abilities bound to an input like this are automatically activated when the input is triggered. This also allows the ability to use the input related ability tasks.

**Comment by ANURAGX** [comment]
I will check it.

**Comment by ANURAGX** [comment]
One more question

Why are you doing this at 2 places. One inside Character and another inside Player Controller.

```AGDPlayerState* PS = GetPlayerState<AGDPlayerState>();
	if (PS)
	{
		// Set the ASC on the Server. Clients do this in OnRep_PlayerState()
		AbilitySystemComponent = Cast<UGDAbilitySystemComponent>(PS->GetAbilitySystemComponent());

		// AI won't have PlayerControllers so we can init again here just to be sure. No harm in initing twice for heroes that have PlayerControllers.
		PS->GetAbilitySystemComponent()->InitAbilityActorInfo(PS, this);

**Comment by tranek** [comment]
The `InitAbilityActorInfo()`? It might be redundant and that's okay. I think I made the `PlayerController` version first thinking that I would catch all new pawns but then realized when making the `GDHeroCharacter` that the AI don't have `PlayerControllers` so they needed to init the ASC either in `AIController` or in the `GDHeroCharacter`.

I would expect if you just have the one in `GDHeroCharacter` that you'll be fine and cover every scenario.

**Comment by tranek** [comment]
I'll add that it also guarantees that the player's ASC (on the `PlayerState`) always has a valid `AvatarActor`. I'm not sure if that matters or not.

**Comment by ANURAGX** [comment]
```UENUM(BlueprintType)
enum class EGDAbilityInputID : uint8
{
	// 0 None
	None			UMETA(DisplayName = "None"),
	// 1 Confirm
	Confirm			UMETA(DisplayName = "Confirm"),
	// 2 Cancel
	Cancel			UMETA(DisplayName = "Cancel"),
	// 3 LMB
	Ability1		UMETA(DisplayName = "Ability1"),
	// 4 RMB
	Ability2		UMETA(DisplayName = "Ability2"),
	// 5 Q
	Ability3		UMETA(DisplayName = "Ability3"),
	// 6 E
	Ability4		UMETA(DisplayName = "Ability4"),
	// 7 R
	Ability5		UMETA(DisplayName = "Ability5"),
	// 8 Sprint
	Sprint			UMETA(DisplayName = "Sprint"),
	// 9 Jump
	Jump			UMETA(DisplayName = "Jump")
};


Does this need to be exact same as that of Binding from editor.

![image](https://user-images.githubusercontent.com/5199691/71480560-cd332600-281f-11ea-935c-261a1a7826be.png)

**Comment by ANURAGX** [comment]
Will it handle the touch inputs as well.

**Comment by tranek** [comment]
Yes, the struct members need to be the exact same except for Confirm/Cancel. Please read the README which explains this in more detail. https://github.com/tranek/GASDocumentation#concepts-ga-input

I am not sure about touch inputs, you'll have to check the source code.

**Comment by ANURAGX** [comment]
What will happen if i m handling input actions as usual along with Gameplay bindings?

**Comment by tranek** [comment]
It'll be fine. If you handle input actions that are also handled by the ASC, make sure that you don't consume the input otherwise they won't reach the ASC.

**Comment by ANURAGX** [comment]
Finally I wrote my own JumpingAbility and its working really great. All Thanks to you.

**Comment by ANURAGX** [comment]
Adding touch 1 along with spacebar in the input for Jump makes it jump on mobile devices.
