### ISSUE TITLE
Raw pointers has been changed by TObjectPtr<>

### ISSUE THREAD

**Issue by AlfieAllen** [tranek/GASDocumentation#81]
Hello dear tutorial creator!

Your tutorial is great, even best.

But In new ue5 rules https://docs.unrealengine.com/5.0/en-US/unreal-engine-5-migration-guide/ Epic Games tells us to replace raw pointers to TObjectPtr<>, so looks like you should do it.

Best Regards

**Comment by tranek** [comment]
Hello, using TObjectPtr<> isn't required and there's not really a compelling reason to use them. Epic's own Lyra sample project doesn't use them. I won't be making that change, thanks though.
