### ISSUE TITLE
AGDPlayerState::HealthChanged() delegate firing non-stop

### ISSUE THREAD

**Issue by AlfieAllen** [tranek/GASDocumentation#82]
![image](https://user-images.githubusercontent.com/31819230/170330203-3ef74f43-01fb-4f45-a86c-16d0e177d388.png)

Hello I found suspicious behavior... Looks like HealthChangedDelegateHandle inside of GDPlayerState firing non-stop (2-3 times per second) even without any Health changing.

It is okay, or bug?

**Comment by LoborchukAndrii** [comment]
I think it's call health regeneration.

**Comment by tranek** [comment]
Yes, it's from the health regen GE. If you put a breakpoint there, you can see it in the Data parameter.
![image](https://user-images.githubusercontent.com/1534735/219905205-d4c8f7fb-a1fa-4cfb-a8a2-808a0716cc75.png)

This is as expected. In a production game, you can optimize this by setting an OngoingTagRequirement in the HealthRegen GE to pause the GE while the player has full health. You'd have to manually add a tag to the player when they have full health and remove it when they do not have full health.
