### ISSUE TITLE
Meteor CommitAbility

### ISSUE THREAD

**Issue by Bradbev** [tranek/GASDocumentation#86]
GA_Meteor_BP doesn't check the return value of CommitAbility, but it seems like it ought to be connected to the immediately following branch.

![2022-09-15 16_20_17-GASDocumentation - Unreal Editor](https://user-images.githubusercontent.com/36225/190313946-763cc6a2-7cec-40bc-bb8f-e507de6a226e.png)

**Comment by tranek** [comment]
Not sure when or how that got disconnected. Thanks!

**Comment by Bradbev** [comment]
Thank you for this fantastic learning resource! :)
