### ISSUE TITLE
Basic Combo Attack Ability.

### ISSUE THREAD

**Issue by ANURAGX** [tranek/GASDocumentation#9]
Hi 
I need some guidance regarding setting up new Ability and Ability Task.

So What I m doing is I have 3 montages to play for a basic combo attack move.
And that combo attack is one ability.
So my concern how do I play montage. I have figured out few options
1. Fire AbilityTaskToPlayMontage when the BasicComboAttackAbility is triggered.
2. When BasicComboAttackAbility is triggered play a simple montage inside of character class.

I prefer C++.

**Comment by ANURAGX** [comment]
Sorry, I found this class which perfectly answers my question.
UGDGA_FireGun

**Comment by ANURAGX** [comment]
So in your UGDGA_FireGun class,
you didn't override the CanActivateAbility function, so it means that the ability will be activated as my times the user clicks. -> Fine as per the Gun requirement.

So what happens to the montage task which is already doing its task and upon activation of ability one new montage task is executed.

Will the old montage task will fire onInterrupted event.

**Comment by tranek** [comment]
Hi, please keep GitHub repository issues related to actual problems with the project itself. If you have questions about GAS, try the Unreal Engine forums, AnswerHub, or Unreal Slackers Discord.
