### ISSUE TITLE
Fix the About section

### ISSUE THREAD

**Issue by WizardCell** [tranek/GASDocumentation#91]
Currently the About section mentions "Unreal Engine 4's", as can be seen below:

![image](https://user-images.githubusercontent.com/25373592/202253578-97c6712e-7954-4d0a-a146-95fde7e47fd5.png)

<br>

While in fact the Readme section mentions "Unreal Engine 5's", which is imo the correct version:

![image](https://user-images.githubusercontent.com/25373592/202253428-6ccb0c0d-cc41-453e-8ff3-5defcd03e002.png)

The correct version is the latter, and I think the former should be fixed so it conforms with the latter.

**Comment by tranek** [comment]
Fixed, thank you!
