### ISSUE TITLE
Applying Gameplay Tags in Execution Calculation Class

### ISSUE THREAD

**Issue by MustafaNizamettinKablama** [tranek/GASDocumentation#96]
I want to apply Gameplay Tag in ExecutionCalculation but it doesn't work in client side.
This is a necessary for my project and I can't fix it. Can you help me?

![ExexCalc2](https://user-images.githubusercontent.com/111287760/209676823-ada81f20-877f-4518-a2c3-ef8c834350f1.png)

**Comment by tranek** [comment]
These Issues are only for the GASDocumentation repository - README and Sample Project, not for help with personal projects. Try the Unreal Engine forums or the Unreal Slackers Discord.
